# Generated by Django 4.2.3 on 2024-07-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_sitesettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
