# Generated by Django 4.2.3 on 2024-07-14 07:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_sitesettings_logo_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=350)),
                ('background_image', models.ImageField(upload_to='banner-image/')),
                ('bg_image_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='banner-image/')),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('publish', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
