# Generated by Django 4.2.3 on 2024-07-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_homebanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebanner',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='homebanner',
            name='modified_at',
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
