# Generated by Django 4.2.3 on 2024-07-13 17:16

from django.db import migrations, models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('short_description', models.TextField(default='', max_length=100)),
                ('description', tinymce.models.HTMLField()),
                ('image1', models.ImageField(upload_to='services/items/')),
                ('image1_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('image2', models.ImageField(upload_to='services/items/')),
                ('image2_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.TextField(blank=True, max_length=3000, null=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('publish', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-priority',),
            },
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('sub_title', models.TextField()),
                ('image', models.ImageField(upload_to='services')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
