# Generated by Django 4.2.3 on 2024-07-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_servicepage_image_servicepage_sub_titless'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='sub_titless',
        ),
    ]
