# Generated by Django 4.2.3 on 2024-07-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_servicepage_sub_titless'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
