# Generated by Django 4.2.3 on 2024-07-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_is_deleted_servicepage_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='is_deleted',
        ),
    ]
