# Generated by Django 4.2.3 on 2024-07-14 01:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_service_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image1_alt',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image2_alt',
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='services/items/')),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('publish', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service')),
            ],
            options={
                'ordering': ('-priority',),
            },
        ),
    ]
