# Generated by Django 4.2.3 on 2024-07-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_service_image1_remove_service_image1_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='home_description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
