# Generated by Django 4.2.3 on 2024-07-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servicepage_home_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='logo',
            field=models.ImageField(default='', upload_to='services/logo/'),
            preserve_default=False,
        ),
    ]
