# Generated by Django 4.2.3 on 2024-07-14 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogimage',
            old_name='service',
            new_name='blog',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='home_description',
        ),
    ]
