# Generated by Django 4.2.3 on 2024-07-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_service_blogimage_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
